name = "code-stack-on-cloudflare"
compatibility_date = "2024-11-11"
# Enable Node.js compat so Next.js route handlers using Node APIs work
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false

[vars]
# Add any runtime env vars here or in Project Settings on Cloudflare

[pages]
# The output folder produced by `next-on-pages build`
# You do not need to change this unless you alter the build command.
build_output_dir = ".vercel/output/static"
